### PR TITLE
add autocompletion support to OSM Scout nearby search

### PR DESCRIPTION
**Pull request by rinigus**
This PR adds autocomplete support for OSM Scout nearby type. It uses new API for autocompletion and should be considered instead of earlier implementation at https://github.com/otsaloma/whogo-maps/pull/40 .

I am going to close the [other PR](https://github.com/otsaloma/whogo-maps/pull/40)

### CODE REVIEW

**Comment by rinigus** [comment]
I have also restored history for name parameter in nearby search for OSM Scout. It was broken due to improvements in `findMatches`

**Comment by otsaloma** [comment]
For what it's worth, I chose not to do that unicodedata normalization myself as it doesn't really make a distinction between different letters vs. accents and just changes all, e.g. "ä" to "a", which is quite unnatural, at least for Finnish and Swedish. That's why I did just the "café" special case. The rest looks fine, so if the normalization is intentional, I can merge.

**Comment by otsaloma** [comment]
Oh, that's not the same unicodedata normalization I tried. What does your code actually do?

**Comment by rinigus** [comment]
Since I am pulling OSM types synonyms for all kind of languages (see list at https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases), the server provides the list for POI types in accordance to the locale and languages selected by the user.  So, I had to compare unicode strings properly:

NFKC enshures that é will be the same irrespective to how its written. However, it does not strip ¨ from ä, just represents it in a canonical way. Case folding is similar to lowercase, but for any utf-8 chars. So, its common to do NFKC and case folding later. There will be false positives, I imagine, since ß is transferred to `ss` => s will be hitting it too.But that's a small price to pay for being able to cover Latin, Cyrillic and other alphabets. For background, see https://www.elastic.co/guide/en/elasticsearch/guide/current/case-folding.html and Normalization at https://en.wikipedia.org/wiki/Unicode_equivalence

However, it doesn't strip the accents nor transliterate. Although, with autocomplete, I don't think you need to worry about Café anymore - I would type "Caf" and choose Café from the list.

So, to reply to the question: yes, normalization is intentional

**Comment by otsaloma** [comment]
Okay, thanks, merging.

**Comment by rinigus** [comment]
Thank you! Nice job on all this autocomplete support - was very easy to use it!

**Pull request merged**
