### PR TITLE
fix syntax es.po

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by otsaloma** [comment]
1. Why the change? Is "Recalcular ruta" too long? It should wrap nicely to separate lines, does it?

1. Can you please make these changes at [Transifex](https://www.transifex.com/otsaloma/whogo-maps/)? The translation files are up-to-date on Transifex and synced to GitHub only at release time. Also, it's nicer for the other translators that changes happen openly in one place and are properly tracked.

**Comment by ghost** [comment]
It is just for following syntax,  "Recalcular ruta" is  too long. "Recalcular" is perfect :  )
I do not use transifex : (
Look this >>
captura_20180610_001

**Comment by otsaloma** [comment]
It seems the Spanish translation has not been modified at Transifex, so I'll make an exception and merge this and push the change to Transifex. But, spread the word, this is not the way to update translations and further translation PRs are liable to be rejected.

**Comment by ghost** [comment]
I know.  I thankful

**Pull request merged**
